<?php

function search_form_api_rerender($textfield, $submit, $vars) {
  foreach ($textfield as $attribute => $value):
    $vars['form']['search_theme_form']["#$attribute"] = t($value);
  endforeach;
  
  unset($vars['form']['search_theme_form']['#printed']);
  $vars['search']['search_theme_form'] = drupal_render($vars['form']['search_theme_form']);

  foreach ($submit as $attribute => $value):
    $vars['form']['submit']["#$attribute"] = t($value);
  endforeach;

  if (isset($submit['type'])):
    if ($submit['type'] == 'image_button' and isset($submit['src'])):
      $vars['form']['submit']['#src'] = path_to_theme() . $submit['src'];
    endif;
  endif;
  
  unset($vars['form']['submit']['#printed']);
  $vars['search']['submit'] = drupal_render($vars['form']['submit']);
  
  $vars['search_form'] = implode($vars['search']);
}

function search_form_api_add_clear_script() {
  return drupal_add_js(drupal_get_path('module', 'search_theme_api') . '/clear_search_form.js');
}
